// <auto-generated />
using DDACCharityServices.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDACCharityServices.Migrations.DDACCharityServicesForBackground
{
    [DbContext(typeof(DDACCharityServicesForBackgroundContext))]
    partial class DDACCharityServicesForBackgroundContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DDACCharityServices.Models.Background", b =>
                {
                    b.Property<int>("BackgroundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BackgroundAmount")
                        .HasColumnType("int");

                    b.Property<string>("BackgroundDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("BackgroundName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BackgroundStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomUserModelEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BackgroundID");

                    b.ToTable("Background");
                });
#pragma warning restore 612, 618
        }
    }
}
